### ISSUE TITLE
Move CommandHandler execution into static queue

### ISSUE THREAD

**Issue by ScottLilly** [ScottLilly/MegaCorpClash#217]

**Comment by jimf99** [comment]
Hello Scott.

Would you use something like this for the Static Queue?

https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.queue-1?view=net-6.0

From: Twitch.tv JimFyyc

**Comment by ScottLilly** [comment]
@jimf99 This will probably use a ConcurrentQueue<BaseCommandHandler>, which is thread-safe (https://learn.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentqueue-1?view=net-6.0)
