### ISSUE TITLE
Change !incorporate to !start

### ISSUE THREAD

**Issue by ScottLilly** [ScottLilly/MegaCorpClash#221]
Or some easier/shorter word

**Comment by gbowne1** [comment]
Idk.  I like incorporate which could be shortened to !inc  but start is ok too.

**Comment by ScottLilly** [comment]
I don't know if "start" will ultimately be the word, but I want to have a shorter option than "incorporate"

**Comment by gbowne1** [comment]
Imho, inc would be a good short option most people will understand.  A variation could just be !co
